site_name: 《Data Mining》中文版

# Contents
pages:
  - 首页: index.md
  - 第1章 绪论: 1.md
  - 第2章 数据预处理: 2.md
  - 第3章 相似度和距离: 3.md
  - 第4章 关联模式挖掘: 4.md
  - 第5章 关联模式挖掘高级概念: 5.md
  - 第6章 聚类分析: 6.md
  - 第7章 聚类分析：高级概念: 7.md
  - 第8章 异常值分析: 8.md
  - 第9章 异常值分析：高级概念: 9.md
  - 第10章 数据分类: 10.md
  - 第11章 数据分类：高级概念: 11.md
  - 第12章 数据流挖掘: 12.md
  - 第13章 挖掘文本数据: 13.md
  - 第14章 挖掘时间序列数据: 14.md
  - 第15章 离散序列挖掘: 15.md
  - 第16章 空间数据挖掘: 16.md
  - 第17章 图数据挖掘: 17.md
  - 第18章 Web数据挖掘: 18.md
  - 第19章 社交网络分析: 19.md
  - 第20章 数据挖掘中的隐私保护: 20.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

#
extra_javascript:
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
# markdown_extensions


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
